#!/usr/bin/env python3
"""Render site/index.html from manifest.yaml and sync images.

Pattern mirrors postcards/quietwake build step:
  1. Read manifest.yaml.
  2. Compute day_index from (today_utc - launch_date) + 1, clamped >= 0.
  3. Render site/index.html from a template.
  4. Unconditional cp -f images/*.jpg site/images/ so the deploy
     always carries the current image set (avoids the
     stale-image-in-site-dir failure mode).

Run via: uv run python build.py   (no deps; stdlib only after yaml)
Or:      python3 build.py         (requires PyYAML).
"""

from __future__ import annotations

import datetime as dt
import html
import shutil
import sys
from pathlib import Path

try:
    import yaml  # type: ignore[import-not-found]
except ImportError:
    sys.stderr.write(
        "PyYAML missing. install via: uv add pyyaml   OR   pip install pyyaml\n"
    )
    sys.exit(2)

ROOT = Path(__file__).resolve().parent
MANIFEST = ROOT / "manifest.yaml"
SITE = ROOT / "site"
IMAGES_SRC = ROOT / "images"
IMAGES_DST = SITE / "images"


def render(manifest: dict) -> str:
    launch_date = manifest.get("launch_date")
    if isinstance(launch_date, str):
        launch_date = dt.date.fromisoformat(launch_date)
    today = dt.datetime.now(dt.timezone.utc).date()
    scenes = manifest.get("scenes") or []
    day_count = len(scenes)
    since_str = launch_date.isoformat() if launch_date else "—"

    if day_count == 0:
        header_main = "day 0"
        empty_state = (
            '<p class="empty">collection begins soon</p>'
        )
        tiles_html = ""
    else:
        header_main = f"day {day_count}"
        empty_state = ""
        # render newest first — most recent at top
        tile_lines = []
        for scene in reversed(scenes):
            date = html.escape(str(scene.get("date", "")))
            img = html.escape(str(scene.get("image", "")))
            tile_lines.append(
                '<figure class="tile">'
                f'<a href="images/{img}" target="_blank" rel="noopener">'
                f'<img src="images/{img}" loading="lazy" '
                f'alt="thonk for {date}" />'
                f'<figcaption>{date}</figcaption>'
                "</a></figure>"
            )
        tiles_html = "\n".join(tile_lines)

    repo_url = "https://github.com/prmichaelsen/thonk"

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>thonk — one new thonk emoji per day</title>
<meta name="description" content="one new thonk emoji per day, generated by replicate google/nano-banana, accumulating into a tile grid. since {since_str}." />
<link rel="stylesheet" href="style.css" />
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🤔</text></svg>" />
</head>
<body>
<header>
  <h1>thonk</h1>
  <p class="status">{header_main} &middot; since {since_str}</p>
</header>
<main>
{empty_state}
<section class="grid" aria-label="thonk collection">
{tiles_html}
</section>
</main>
<footer>
  <a href="#about">about</a>
  <span aria-hidden="true">&middot;</span>
  <a href="{repo_url}">github</a>
</footer>
<section id="about" class="about">
  <h2>about</h2>
  <p>one new thonk emoji per day. each day at ~00:10 UTC, a
  controlled-axis prompt rotation picks a style modifier and asks
  replicate's google/nano-banana for a single emoji-style
  illustration of a thonk face. the result is committed here and
  deployed. no curation, no resubmits — what comes out is what
  ships. the variance is the value.</p>
  <p>read-only collection. no accounts. no votes. no comments. one
  tile a day, growing on its own.</p>
  <p>made by <a href="https://reflecttech.ai">reflection</a>. source
  at <a href="{repo_url}">github.com/prmichaelsen/thonk</a>.</p>
</section>
</body>
</html>
"""


def sync_images() -> None:
    IMAGES_DST.mkdir(parents=True, exist_ok=True)
    if not IMAGES_SRC.exists():
        return
    for pattern in ("*.png", "*.jpg"):
        for img in IMAGES_SRC.glob(pattern):
            shutil.copy2(img, IMAGES_DST / img.name)


def main() -> int:
    if not MANIFEST.exists():
        sys.stderr.write(f"manifest not found at {MANIFEST}\n")
        return 1
    manifest = yaml.safe_load(MANIFEST.read_text()) or {}
    SITE.mkdir(parents=True, exist_ok=True)
    sync_images()
    (SITE / "index.html").write_text(render(manifest))
    scene_count = len(manifest.get("scenes") or [])
    print(f"build ok — day {scene_count}, {scene_count} tiles rendered")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
